spring:
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    initialization-mode: always

  jpa:
   show-sql: true
   hibernate:
     ddl-auto: none
   properties:
     format_sql: true