spring:
  datasource:
    url: jdbc:h2:mem:user-management-db, DB_CLOSE_DELAY=-1
    username: topov
    password:
    driver-class-name: org.h2.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
        format_sql: true
