server:
  port: 8080
  servlet:
    context-path: /user-management

spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/h2/databases/user-management-db
    username: topov
    password: admin
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      format_sql: true
